# Generated by Django 4.1.5 on 2023-01-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_created_profile_location_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
